#Eureka Server location is taken from Spring Cloud Config Server
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: "http://localhost:8010/eureka/"

#Moved to github fof Config Server
#words: "ran,knew,had,saw,bought"

server:
  port: ${PORT:${SERVER_PORT:0}}
